name: PR Trigger Example
on:
  pull_request:           # Trigger on PR events
    types: [opened, synchronize, reopened]  # Specific PR activities
    branches:             # Target branches for PR
      - main             # Only PRs targeting main branch
    paths:               # File paths that trigger workflow
      - '**.js'          # Any JavaScript file changes
      - '**.ts'          # Any TypeScript file changes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Testing PR    # ${{ github.event.pull_request.number }}"  # PR number
